server:
  port: 8080
  error:
    path: /error
  servlet:
    context-path: /chapter02
    session:
      timeout: 30m
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
#  ssl:
#    key-store: allen.p12
#    key-alias: tomcathttps
#    key-store-password: 123456


my:
  name: allen
  address: 广州
  favorites:
    - 跑步
    - 唱歌


spring:
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    encoding: UTF-8
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
#============== 大数据kafka对接配置 ===================
  kafka:
    bootstrap-servers: 192.168.181.140:9093
    producer:
      # 设置大于0的值，则客户端会将发送失败的记录重新发送
      acks: 0
      retries: 0
      # 每次批量发送消息的数量
      #spring.kafka.producer.batch-size=16384
      #spring.kafka.producer.buffer-memory=33554432
      # 指定消息key和消息体的编解码方式 UTF-8
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    # Kafka Consumer Listener 监听器配置
    listener:
      missing-topics-fatal: false # 消费监听接口监听的主题不存在时，默认会报错。所以通过设置为 false ，解决报