/**
* The following code is automatically generated by the program . 
* Do not modify it manually !
*/
package com.allen.springbootaurhority.entity;

public class Role {
	private int id;
	/**
	 * 职位名称
	 */
	private String name;
	/**
	 * 职位中文名称
	 */
	private String nameZh;
	/**
	 * 创建时间
	 */
	private java.time.LocalDateTime createtime;
	/**
	 * 修改时间
	 */
	private String updatetime;

	public int getId() {	return this.id;	}
	public void setId(int id) {	this.id = id;	}
	public String getName() {	return this.name;	}
	public void setName(String name) {	this.name = name;	}
	public String getNameZh() {	return this.nameZh;	}
	public void setNameZh(String nameZh) {	this.nameZh = nameZh;	}
	public java.time.LocalDateTime getCreatetime() {	return this.createtime;	}
	public void setCreatetime(java.time.LocalDateTime createtime) {	this.createtime = createtime;	}
	public String getUpdatetime() {	return this.updatetime;	}
	public void setUpdatetime(String updatetime) {	this.updatetime = updatetime;	}

}
