/**
* The following code is automatically generated by the program . 
* Do not modify it manually !
*/
package com.allen.springbootaurhority.entity;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

public class SysUser implements UserDetails {
	private int id;
	/**
	 * 用户名
	 */
	private String username;
	/**
	 * 密码
	 */
	private String password;
	/**
	 * 是否可用
	 */
	private boolean enabled;
	/**
	 * 是否锁定
	 */
	private boolean locked;
	/**
	 * 角色列表
	 */
	private List<Role> roles;

	/**
	 * 创建时间
	 */
	private java.time.LocalDateTime createtime;
	/**
	 * 修改时间
	 */
	private java.time.LocalDateTime updatetime;


	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		List<SimpleGrantedAuthority> authorities = new ArrayList<>();

		for ( Role role : roles ){
			authorities.add(new SimpleGrantedAuthority(role.getName()));
		}

		return authorities;
	}

	@Override
	public boolean isAccountNonExpired() {
		return true;
	}

	@Override
	public boolean isAccountNonLocked() {
		return !locked;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		return true;
	}

	@Override
	public boolean isEnabled() {
		return enabled;
	}

	public int getId() {	return this.id;	}
	public void setId(int id) {	this.id = id;	}
	@Override
	public String getUsername() {	return this.username;	}
	public void setUsername(String username) {	this.username = username;	}
	@Override
	public String getPassword() {	return this.password;	}
	public void setPassword(String password) {	this.password = password;	}
	public boolean getEnabled() {	return this.enabled;	}
	public void setEnabled(boolean enabled) {	this.enabled = enabled;	}
	public boolean getLocked() {	return this.locked;	}
	public void setLocked(boolean locked) {	this.locked = locked;	}
	public java.time.LocalDateTime getCreatetime() {	return this.createtime;	}
	public void setCreatetime(java.time.LocalDateTime createtime) {	this.createtime = createtime;	}
	public java.time.LocalDateTime getUpdatetime() {	return this.updatetime;	}
	public void setUpdatetime(java.time.LocalDateTime updatetime) {	this.updatetime = updatetime;	}
	public boolean isLocked() {
		return locked;
	}

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}
}
