/**
* The following code is automatically generated by the program . 
* Do not modify it manually !
*/
package com.allen.springbootaurhority.entity;

public class UserRole {
	/**
	 * 主键ID
	 */
	private int id;
	/**
	 * 用户ID
	 */
	private int uid;
	/**
	 * 角色ID
	 */
	private int rid;

	public int getId() {	return this.id;	}
	public void setId(int id) {	this.id = id;	}
	public int getUid() {	return this.uid;	}
	public void setUid(int uid) {	this.uid = uid;	}
	public int getRid() {	return this.rid;	}
	public void setRid(int rid) {	this.rid = rid;	}

}
