spring:
  mail:
    host: smtp.qq.com
    username: 872062426@qq.com
    password: jceoecmqodulbajj
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
    port: 465
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://192.168.181.140:3306/sakila?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql

  batch:
    job:
      enabled: false
    initialize-schema: always


